(custom-set-variables
 '(org-agenda-compact-blocks nil)
 '(org-agenda-dim-blocked-tasks nil)
 '(org-agenda-files (quote ("~/org/shopping-list.org" "~/org/anniv.org" "~/org/classes.org" "~/org/tasks.org" "~/org/main.org")))
 '(org-agenda-restore-windows-after-quit t)
 '(org-agenda-skip-additional-timestamps-same-entry nil)
 '(org-agenda-skip-deadline-prewarning-if-scheduled 7)
 '(org-agenda-skip-scheduled-if-deadline-is-shown (quote not-today))
 '(org-agenda-start-on-weekday 0)
 '(org-agenda-time-grid (quote ((daily today require-timed remove-match) "----------------" (800 1000 1200 1400 1600 1800 2000))))
 '(org-agenda-todo-list-sublevels nil)
 '(org-agenda-window-setup (quote reorganize-frame))
 '(org-archive-location "~/org/archive.org::* From %s")
 '(org-archive-save-context-info (quote (time file category todo priority itags olpath ltags)))
 '(org-auto-align-tags t)
 '(org-completion-use-ido t)
 '(org-deadline-warning-days 7)
 '(org-default-notes-file "main.org")
 '(org-directory "~/org")
 '(org-drawers (quote ("PROPERTIES" "CLOCK" "LOGBOOK" "DESCRIPTION")))
 '(org-enforce-todo-checkbox-dependencies t)
 '(org-enforce-todo-dependencies nil)
 '(org-export-html-inline-images t)
 '(org-export-with-archived-trees nil)
 '(org-file-apps (quote ((auto-mode . emacs) ("\\.x?html?\\'" . system) ("\\.pdf\\'" . system) (system . "xdg-open"))))
 '(org-hide-leading-stars t)
 '(org-id-locations-file "~/.emacs.d/persistence/.org-id-locations")
 '(org-link-frame-setup (quote ((vm . vm-visit-folder-other-frame) (gnus . gnus-other-frame) (file . find-file))))
 '(org-log-into-drawer t)
 '(org-modules (quote (org-info)))
 '(org-mouse-features (quote (context-menu move-tree yank-link activate-stars activate-bullets activate-checkboxes)))
 '(org-odd-levels-only t)
 '(org-outline-path-complete-in-steps nil)
 '(org-priority-faces (quote ((65 :foreground "red" :weight bold) (66 :foreground "green4" :weight bold) (67 :foreground "blue" :weight bold))))
 '(org-refile-targets (quote ((org-agenda-files :maxlevel . 10))))
 '(org-refile-use-outline-path t)
 '(org-remember-default-headline "Notes")
 '(org-return-follows-link t)
 '(org-reverse-note-order t)
 '(org-support-shift-select t)
 '(org-tags-column-auto-adjust t)
 '(org-todo-keyword-colors (quote (("IN PROGRESS" . "dark orange") ("WAITING" . "red4") ("CANCELED" . "saddle brown"))))
 '(org-todo-keyword-faces (quote (("IN PROGRESS" . "dark orange") ("BLOCKED" . "red3") ("WAITING" . "red4") ("CANCELED" . "saddle brown"))))
 '(org-todo-keywords (quote ((sequence "TODO(t!)" "IN PROGRESS(p!)" "BLOCKED(b!)" "WAITING(w@/!)" "TURN IN(i!)" "|" "DONE(d!)" "CANCELED(c@)"))))
 '(org-todo-keywords-sort-order (quote ("IN PROGRESS")))
 '(org-treat-S-cursor-todo-selection-as-state-change nil)
 '(org-use-fast-todo-selection t)
 '(org-yank-adjusted-subtrees t)
 )
